# These are supported funding model platforms
# Check the official documentation for more information
# https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository
